###Data fields

Here's a brief version of what you'll find in the data description file.

* SalePrice - the property's sale price in dollars. This is the target variable that you're trying to predict.
* MSSubClass: The building class
* MSZoning: The general zoning classification
* LotFrontage: Linear feet of street connected to property
* LotArea: Lot size in square feet
* Street: Type of road access
* Alley: Type of alley access
* LotShape: General shape of property
* LandContour: Flatness of the property
* Utilities: Type of utilities available
* LotConfig: Lot configuration
* LandSlope: Slope of property
* Neighborhood: Physical locations within Ames city limits
* Condition1: Proximity to main road or railroad
* Condition2: Proximity to main road or railroad (if a second is present)
* BldgType: Type of dwelling
* HouseStyle: Style of dwelling
* OverallQual: Overall material and finish quality
* OverallCond: Overall condition rating
* YearBuilt: Original construction date
* YearRemodAdd: Remodel date
* RoofStyle: Type of roof
* RoofMatl: Roof material
* Exterior1st: Exterior covering on house
* Exterior2nd: Exterior covering on house (if more than one material)
* MasVnrType: Masonry veneer type
* MasVnrArea: Masonry veneer area in square feet
* ExterQual: Exterior material quality
* ExterCond: Present condition of the material on the exterior
* Foundation: Type of foundation
* BsmtQual: Height of the basement
* BsmtCond: General condition of the basement
* BsmtExposure: Walkout or garden level basement walls
* BsmtFinType1: Quality of basement finished area
* BsmtFinSF1: Type 1 finished square feet
* BsmtFinType2: Quality of second finished area (if present)
* BsmtFinSF2: Type 2 finished square feet
* BsmtUnfSF: Unfinished square feet of basement area
* TotalBsmtSF: Total square feet of basement area
* Heating: Type of heating
* HeatingQC: Heating quality and condition
* CentralAir: Central air conditioning
* Electrical: Electrical system
* 1stFlrSF: First Floor square feet
* 2ndFlrSF: Second floor square feet
* LowQualFinSF: Low quality finished square feet (all floors)
* GrLivArea: Above grade (ground) living area square feet
* BsmtFullBath: Basement full bathrooms
* BsmtHalfBath: Basement half bathrooms
* FullBath: Full bathrooms above grade
* HalfBath: Half baths above grade
* Bedroom: Number of bedrooms above basement level
* Kitchen: Number of kitchens
* KitchenQual: Kitchen quality
* TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
* Functional: Home functionality rating
* Fireplaces: Number of fireplaces
* FireplaceQu: Fireplace quality
* GarageType: Garage location
* GarageYrBlt: Year garage was built
* GarageFinish: Interior finish of the garage
* GarageCars: Size of garage in car capacity
* GarageArea: Size of garage in square feet
* GarageQual: Garage quality
* GarageCond: Garage condition
* PavedDrive: Paved driveway
* WoodDeckSF: Wood deck area in square feet
* OpenPorchSF: Open porch area in square feet
* EnclosedPorch: Enclosed porch area in square feet
* 3SsnPorch: Three season porch area in square feet
* ScreenPorch: Screen porch area in square feet
* PoolArea: Pool area in square feet
* PoolQC: Pool quality
* Fence: Fence quality
* MiscFeature: Miscellaneous feature not covered in other categories
* MiscVal: $Value of miscellaneous feature
* MoSold: Month Sold
* YrSold: Year Sold
* SaleType: Type of sale
* SaleCondition: Condition of sale

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("train.csv")
df.head()

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]

In [ ]:
print("The shape of the dataset: {}".format(df.shape))

The shape of the dataset: (1459, 80)

Count missing values

Using a four loop, we can figure out the number of missing values in each column

.value_counts() - Return a Series containing counts of unique values.

In [ ]:
missing_data = df.isnull()
columns_missing_data = []
for column in df.columns.values.tolist():
  columnn_missing_data = missing_data[column].value_counts()
  if len(columnn_missing_data) == 2:
    print(column)
    print(columnn_missing_data)
    print("")
    columns_missing_data.append(column)

print("These columns have missing data:")
print(columns_missing_data)

MSZoning
False    1455
True        4
Name: MSZoning, dtype: int64

LotFrontage
False    1232
True      227
Name: LotFrontage, dtype: int64

Alley
True     1352
False     107
Name: Alley, dtype: int64

Utilities
False    1457
True        2
Name: Utilities, dtype: int64

Exterior1st
False    1458
True        1
Name: Exterior1st, dtype: int64

Exterior2nd
False    1458
True        1
Name: Exterior2nd, dtype: int64

MasVnrType
False    1443
True       16
Name: MasVnrType, dtype: int64

MasVnrArea
False    1444
True       15
Name: MasVnrArea, dtype: int64

BsmtQual
False    1415
True       44
Name: BsmtQual, dtype: int64

BsmtCond
False    1414
True       45
Name: BsmtCond, dtype: int64

BsmtExposure
False    1415
True       44
Name: BsmtExposure, dtype: int64

BsmtFinType1
False    1417
True       42
Name: BsmtFinType1, dtype: int64

BsmtFinSF1
False    1458
True        1
Name: BsmtFinSF1, dtype: int64

BsmtFinType2
False    1417
True       42
Name: BsmtFinType2, dtype: int64

BsmtFinSF2
False    1458
True        1
Name: BsmtFinSF2, dtype: int64

BsmtUnfSF
False    1458
True        1
Name: BsmtUnfSF, dtype: int64

TotalBsmtSF
False    1458
True        1
Name: TotalBsmtSF, dtype: int64

BsmtFullBath
False    1457
True        2
Name: BsmtFullBath, dtype: int64

BsmtHalfBath
False    1457
True        2
Name: BsmtHalfBath, dtype: int64

KitchenQual
False    1458
True        1
Name: KitchenQual, dtype: int64

Functional
False    1457
True        2
Name: Functional, dtype: int64

FireplaceQu
True     730
False    729
Name: FireplaceQu, dtype: int64

GarageType
False    1383
True       76
Name: GarageType, dtype: int64

GarageYrBlt
False    1381
True       78
Name: GarageYrBlt, dtype: int64

GarageFinish
False    1381
True       78
Name: GarageFinish, dtype: int64

GarageCars
False    1458
True        1
Name: GarageCars, dtype: int64

GarageArea
False    1458
True        1
Name: GarageArea, dtype: int64

GarageQual
False    1381
True       78
Name: GarageQual, dtype: int64

GarageCond
False    1381
True       78
Name: GarageCond, dtype: int64

PoolQC
True     1456
False       3
Name: PoolQC, dtype: int64

Fence
True     1169
False     290
Name: Fence, dtype: int64

MiscFeature
True     1408
False      51
Name: MiscFeature, dtype: int64

SaleType
False    1458
True        1
Name: SaleType, dtype: int64

These columns have missing data:
['MSZoning', 'LotFrontage', 'Alley', 'Utilities', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType']

In [ ]:
df[columns_missing_data].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LotFrontage   1201 non-null   float64
 1   Alley         91 non-null     object
 2   MasVnrType    1452 non-null   object
 3   MasVnrArea    1452 non-null   float64
 4   BsmtQual      1423 non-null   object
 5   BsmtCond      1423 non-null   object
 6   BsmtExposure  1422 non-null   object
 7   BsmtFinType1  1423 non-null   object
 8   BsmtFinType2  1422 non-null   object
 9   Electrical    1459 non-null   object
 10  FireplaceQu   770 non-null    object
 11  GarageType    1379 non-null   object
 12  GarageYrBlt   1379 non-null   float64
 13  GarageFinish  1379 non-null   object
 14  GarageQual    1379 non-null   object
 15  GarageCond    1379 non-null   object
 16  PoolQC        7 non-null      object
 17  Fence         281 non-null    object
 18  MiscFeature   54 non-null     object
dtypes: float64(3), object(16)
memory usage: 216.8+ KB

Columns with missing data:
* LotFrontage 
* Alley
* MasVnrType
* MasVnrArea
* BsmtQual
* BsmtCond
* BsmtExposure
* BsmtFinType1
* BsmtFinType2
* Electrical
* FireplaceQu
* GarageType
* GarageYrBlt
* GarageFinish
* GarageQual
* GarageCond
* PoolQc
* Fence
* Miscfeature


Let's replace the missign values

In [ ]:
#Replace Missing values LotFrontage
meanLontFrontage = df["LotFrontage"].mean()
df["LotFrontage"].replace(np.nan, meanLontFrontage, inplace = True)
print("The mean od the LontFrontage: {}".format(meanLontFrontage))

The mean od the LontFrontage: 70.04995836802642

In [ ]:
#Replace missing values Alley
df["Alley"].replace(np.nan, "NA", inplace = True)

df["Alley"].value_counts()

None    1369
Grvl      50
Pave      41
Name: Alley, dtype: int64

In [ ]:
#Replace missing values MasVnrType
commonMasVnrType = df["MasVnrType"].value_counts().idxmax()
df["MasVnrType"].replace(np.nan, commonMasVnrType, inplace = True)

In [ ]:
#Replace missing values MasVnrArea
meanMasVnrArea = df["MasVnrArea"].mean()
df["MasVnrArea"].replace(np.nan, meanMasVnrArea, inplace = True)

In [ ]:
#Replace missing values BsmtQual
commonBsmtQual = df["BsmtQual"].value_counts().idxmax()
print("the most common BsmtQual: {}".format(commonBsmtQual))

df["BsmtQual"].replace(np.nan, commonBsmtQual, inplace = True)

In [ ]:
#Replace Missing values BsmtCond
commonBsmtCond = df["BsmtCond"].value_counts().idxmax()
print("the most common BsmtCond: {}".format(commonBsmtCond))

df["BsmtCond"].replace(np.nan, commonBsmtCond, inplace = True)

the most common BsmtCond: TA

In [ ]:
#Replace misiing values BsmtExposure
commonBsmtExposure = df["BsmtExposure"].value_counts().idxmax()
print("the most frecuently BsmtExposure: {}".format(commonBsmtExposure))

df["BsmtExposure"].replace(np.nan, commonBsmtExposure, inplace = True)

the most frecuently BsmtExposure: No

In [ ]:
#Replace misiing values BsmtFinType1
commonBsmtFinType1 = df["BsmtFinType1"].value_counts().idxmax()
print("the most frecuently BsmtFinType1: {}".format(commonBsmtFinType1))

df["BsmtFinType1"].replace(np.nan, commonBsmtFinType1, inplace = True)

the most frecuently BsmtFinType1: Unf

In [ ]:
commonBsmtFinType2 = df["BsmtFinType2"].value_counts().idxmax()
print("the most frecuently BsmtFinType2: {}".format(commonBsmtFinType2))

df["BsmtFinType2"].replace(np.nan, commonBsmtFinType2, inplace = True)

the most frecuently BsmtFinType2: Unf

In [ ]:
commonElectrical = df["Electrical"].value_counts().idxmax()
print("the most frecuently Electrical: {}".format(commonElectrical))

df["Electrical"].replace(np.nan, commonElectrical, inplace = True)

the most frecuently Electrical: SBrkr

In [ ]:
print("Number of fireplaces: \n{}".format(df["Fireplaces"].value_counts()))

#Replace FireplaceQu
df["FireplaceQu"].replace(np.nan, "NA", inplace = True)

Number of fireplaces:
0    690
1    650
2    115
3      5
Name: Fireplaces, dtype: int64

In [ ]:
#Replace GarageType
print("GarageType: \n{}".format(df["GarageType"].value_counts()))
print("\nGaragefinish: \n{}".format(df["GarageFinish"].value_counts()))
print("\nGarageCars: \n{}".format(df["GarageCars"].value_counts()))
print("\nGarageArea: \n{}".format(df["GarageArea"].value_counts()))
print("\nGarageQual: \n{}".format(df["GarageQual"].value_counts()))
print("\nGarageCond: \n{}".format(df["GarageCond"].value_counts()))

df[["GarageType", "GarageFinish", "GarageQual", "GarageCond"]].replace(np.nan, "NA", inplace = True)
df["GarageYrBlt"].replace(np.nan, 0, inplace = True)

GarageType:
Attchd     870
Detchd     387
BuiltIn     88
NA          81
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64

Garagefinish:
Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64

GarageCars:
2    824
1    369
3    181
0     81
4      5
Name: GarageCars, dtype: int64

GarageArea:
0       81
440     49
576     47
240     38
484     34
        ..
754      1
459      1
458      1
756      1
1418     1
Name: GarageArea, Length: 441, dtype: int64

GarageQual:
TA    1311
Fa      48
Gd      14
Po       3
Ex       3
Name: GarageQual, dtype: int64

GarageCond:
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [ ]:
#Replace missing values Pool
print("Pool area in square feet: \n{}".format(df["PoolArea"].value_counts()))

df["PoolQC"].replace(np.nan, "NA", inplace = True)

Pool area in square feet:
0      1453
738       1
648       1
576       1
555       1
519       1
512       1
480       1
Name: PoolArea, dtype: int64

In [ ]:
#Replace missing values fence

df["Fence"].replace(np.nan, "NA", inplace = True)

In [ ]:
#Replace missing values misc features
df["MiscFeature"].replace(np.nan, "NA", inplace = True)